CREATE TABLE IF NOT EXISTS member(
    id SERIAL PRIMARY KEY NOT NULL,
    FullName TEXT NOT NULL,
    email TEXT NOT NULL,
    phoneNumber TEXT NOT NULL,
    datejoined TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE member 
ADD COLUMN is_active BOOLEAN NOT NULL;