CREATE TABLE IF NOT EXISTS member(
    id SERIAL PRIMARY KEY NOT NULL,

    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    email TEXT NOT NULL,
    phoneNumber TEXT NOT NULL,
    is_active BOOLEAN NOT NULL,
    branch_id INT NOT NULL REFERENCES branches(id) ON DELETE CASCADE,
    datejoined TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE member DROP COLUMN FullName;
ALTER TABLE member ADD COLUMN first_name TEXT,
ADD COLUMN last_name TEXT;


CREATE TABLE IF NOT EXISTS church (
    id SERIAL PRIMARY KEY NOT NULL,
    name TEXT NOT NULL,
    location TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE branches (
    id SERIAL PRIMARY KEY NOT NULL,
    church_id INT NOT NULL REFERENCES church(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    city TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);